## TensorFlow Basics for Development

In [29]:
###定义tensor变量
# -*- coding:utf-8 -*-
import numpy as np
import tensorflow as tf
a=tf.zeros([2,2])
b=tf.ones([2,2])

## tensorflow定义的变量只有激活后才有值

In [30]:
print(b)

Tensor("ones_3:0", shape=(2, 2), dtype=float32)


In [31]:
###Session()来激活
with tf.Session() as sess:
    print(sess.run(b))

[[1. 1.]
 [1. 1.]]


In [33]:
###对tensor内部元素求和
with tf.Session() as sess:
    print(tf.reduce_sum(b,axis=0))
    print(sess.run(tf.reduce_sum(b,axis=0)))####axis=0表示横向 Vertical
    print(sess.run(tf.reduce_sum(b,axis=1)))####axis=1表示纵向 Horizontal

Tensor("Sum_1:0", shape=(2,), dtype=float32)
[2. 2.]


In [34]:
####求tensor的尺寸大小
print(b.get_shape())

(2, 2)


In [35]:
###Reshape a tensor
with tf.Session() as sess:
    b=tf.reshape(b,(1,-1))####注意理解这里-1的含义
    print(sess.run(b))

[[1. 1. 1. 1.]]


In [40]:
###定义tensorflow常量和变量
c1=tf.constant([1,2,3,4])
W=tf.Variable(tf.random_normal([1,4],-1,1),dtype=tf.float32)
b=tf.Variable(tf.zeros([1,4]))
init=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(c1,'\n',W,'\n',b)
    print(sess.run(c1),'\n',sess.run(W),'\n',sess.run(b))

Tensor("Const_16:0", shape=(4,), dtype=int32) 
 <tf.Variable 'Variable_86:0' shape=(1, 4) dtype=float32_ref> 
 <tf.Variable 'Variable_87:0' shape=(1, 4) dtype=float32_ref>
[1 2 3 4] 
 [[-0.5594664 -1.2576094 -1.4333105 -1.5002048]] 
 [[0. 0. 0. 0.]]


# tensorflow computational operations(ops)
## 注意tf.matmul(matrix multiply) 和 *  的区别

In [41]:
c1=tf.constant([1,2,3,4])
c2=tf.constant([4,3,2,1])
d1=tf.constant([1,2,2,1])
h1=tf.constant([[1,2,3,4],[4,3,2,1]])
h2=tf.constant([[0,1],[2,1],[3,4],[1,0]])
init=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(c1*c2),'\n',sess.run(c1*c2+d1),'\n',sess.run(tf.matmul(h1,h2)))

[4 6 6 4] 
 [5 8 8 5] 
 [[17 15]
 [13 15]]


In [42]:
import numpy as np
import tensorflow as tf
x_=tf.placeholder(tf.float32,[None,2])
y_=tf.placeholder(tf.float32,[None,1])

W1=tf.Variable(tf.random_uniform([2,2]),dtype=tf.float32)
b1=tf.Variable(tf.zeros([2]),dtype=tf.float32)
output1=tf.sigmoid(tf.matmul(x_,W1)+b1)

W2=tf.Variable(tf.random_uniform([2,1]),dtype=tf.float32)
b2=tf.Variable(tf.zeros([1]),dtype=tf.float32)

output2=tf.sigmoid(tf.matmul(output1,W2)+b2)

loss=tf.reduce_mean((y_*tf.log(output2)+(1-y_)*tf.log(1-output2))*-1)

optimizer=tf.train.GradientDescentOptimizer(0.01).minimize(loss)

x=np.array([[1,0],[0,1],[0,0],[1,1]])
y=np.array([[1],[1],[0],[0]])

init=tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    for i in range(100000):
        sess.run(optimizer,feed_dict={x_:x,y_:y})
        #sess.run(loss,feed_dict={x_:x,y_:y})
    print(sess.run(output2,feed_dict={x_:x,y_:y}))

[[0.97349846]
 [0.97349226]
 [0.0308611 ]
 [0.03088498]]
